### ISSUE TITLE
Multi-grained scanning part still exist?

### ISSUE THREAD

**Issue by Lizheng068** [LAMDA-NJU/Deep-Forest#61] opened 2021-03-13 03:28 UTC
Hi.  I want to set the size of the sliding window, but I did not find the code of multi-grained scanning part in DF21. Does the function of multi-grained scanning part exist in DF21? If so, where can I find the corresponding file? Also, I wonder, do subcascades of each cascade still exist, e.g., Level 1A, Level 1B, Level 1C. Look forward to your help. Thank you!

**Comment by xuyxu** [comment] 2021-03-13 05:40
A duplicate of issue #26. Implementing multi-grained scanning is not our main target for now.

**Closed by xuyxu** 2021-03-13 05:40 UTC
