### ISSUE TITLE
Cannot find deep-forest in PyPI

### ISSUE THREAD

**Issue by cloudy-sfu** [LAMDA-NJU/Deep-Forest#129] opened 2023-06-24 15:12 UTC
Python 3.11, ubuntu 20.04 LTS
```
pip install deep-forest -i https://pypi.org/simple
```
It returns
```
ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)
ERROR: No matching distribution found for deep-forest
```

**Comment by xuyxu** [comment] 2023-06-24 15:16
A duplicate of #127

**Closed by xuyxu** 2023-06-24 15:16 UTC

**Comment by cloudy-sfu** [comment] 2023-06-24 16:15
@xuyxu 
I manage to package a wheel in manylinux Python 3.11
[deep_forest-0.1.7-cp311-cp311-linux_x86_64.zip](https://github.com/LAMDA-NJU/Deep-Forest/files/11857552/deep_forest-0.1.7-cp311-cp311-linux_x86_64.zip)
