### ISSUE TITLE
Survival models

### ISSUE THREAD

**Issue by yunwezhang** [LAMDA-NJU/Deep-Forest#71] opened 2021-04-20 06:46 UTC
Hi maintainer,

I am wondering is that possible to cascade random survival forest (maybe a sksurv model) instead of RF in your deep forest model? As in #48, it seems that the supported model types are classification and regression. (or did I miss some parts of those tutorial docs?) 

Thanks.

**Comment by xuyxu** [comment] 2021-04-20 11:34
Hi @yunwezhang, after walking through the [example](https://scikit-survival.readthedocs.io/en/latest/user_guide/random-survival-forest.html) on random survival forest in sksurv, I think the biggest problem on using deep forest in survival analysis tasks is how to design good augmented features. In survival analysis, our main concern is the survival predicting function that takes time steps `t` as the input, right? For now, I cannot figure out how to ingest this into the cascade structure of deep forest.

Since we are not quite familiar with survival analysis, your suggestions would be highly welcomed ;-)

**Comment by yunwezhang** [comment] 2021-04-20 21:07
Hi Yixuan,

Yes, you are right about the time steps, the input part of survival models requires a 2-dim thing as the outcome (time+binary status, where this binary means censored or not) but the output is usually a 1-dim vector, either "risk" or "probability" (as in binary classification).  

As for the augmented feature steps, i assume you are talking about this part in the model structure? 
![image](https://user-images.githubusercontent.com/57333460/115462799-6d5f5a80-a26e-11eb-8206-755ae028e6e9.png)
Is this part corresponding to this part in the paper? 
![image](https://user-images.githubusercontent.com/57333460/115462927-92ec6400-a26e-11eb-9c01-9f20cd68986d.png)
Because to me, if I understand correctly, in the cascade forest part, the augmented features (in-model feature transformation) obtained from each forest are the predicted vectors, which can be obtained from a survival forest (the output survival probability). However, I am not clear about the attached picture part. (I think the 2019 paper has it because it is better for image data....) 

Thank you for looking into it and I am not sure how hard it is to add the random survival model. I am happy to chat with you to see how it goes. In summary, the change for the input data needs to be X (n by p), y (both time and status) and the output is probability vector (could be survival risk, 1 year survival probability, 2 year survival prob, etc.) 😊

**Comment by xuyxu** [comment] 2021-04-21 06:14
Thanks for your kind explanations @yunwezhang.

> As for the augmented feature steps, i assume you are talking about this part in the model structure?
> Is this part corresponding to this part in the paper?

No, the second figure posted by you shows the multi-grained scanning part, which is not included in this package, since tree ensembles are typically not the best choice for structured data such as images or audios. Augmented features refer to part of the input for hidden cascade layers. For classification, they are predicted class probabilities; For regression, they are predicted target values.

Here are three questions that I would like to ask further.
* Is random survival forest the state-of-the-art model for survival analysis.
* To conclude your explanations, what we need to modify is the input format, right? Apart from `X`, we also need to enroll an indicator array on time and status.
* Since you mentioned that  the survival probability could be 1 year, 2 year, .... How could we decide the best number of years to be included as the augmented feature?

**Comment by yunwezhang** [comment] 2021-04-21 07:40
Hi Yixuan,

Thanks for the fast reply. I am aware that the multi-grain scanning is not included and that's why I asked why do you have the part (first figure) in your model structure instead of starting from the cascade forest.

Answer for the further questions:
1. To me, RSF yes. There are some DNN based survival models also considered stated-of-art.  (But RSF has the best performance in general among the several datasets I tried.) 
2. Yes, only modify the input part because the output of the RSF is 1-dim, the probability.
3.  I think both the risk score and the predicted probability can be used as augmented features. (My experience of using RSF is in R but theoretically, both packages are based on the same paper so there will be no difference.) My reading from that package shows that the survival probability is not provided in the predict function though.

**Comment by xuyxu** [comment] 2021-04-21 07:57
> Thanks for the fast reply. I am aware that the multi-grain scanning is not included and that's why I asked why do you have the part (first figure) in your model structure instead of starting from the cascade forest.

The binner in that figure is used to reduce the number of splitting candidates for the sake of acceleration (not used in the original deep forest model). The entire architecture does correspond to the cascade forest structure.

Besides, I have opened up a feature request in sksurv [(link)](https://github.com/sebp/scikit-survival/issues/194), deep forest could benefit from using a mixture of `RandomSurvivalForest` and `ExtraSurvivalTrees` in cascade layers. Let's wait for the response from maintainers of sksurv before formally working on this feature request ;-)

**Comment by yunwezhang** [comment] 2021-04-21 08:03
got it! 
yes, let's wait for the reply. To have that extra injection of randomness, it would be better to have ExtraSurvivalTrees.

**Comment by xuyxu** [comment] 2021-04-23 07:12
Realizing that we can implement `ExtraSurvivalTrees` by importing `sksurv` as a soft dependency, I think we could work on this feature request without extra helps from that  community.

> Thank you for looking into it and I am not sure how hard it is to add the random survival model. I am happy to chat with you to see how it goes. In summary, the change for the input data needs to be X (n by p), y (both time and status) and the output is probability vector (could be survival risk, 1 year survival probability, 2 year survival prob, etc.) 😊

If you are interested in extending deep forest to the field of survival analysis, could you contact me through an e-mail [(Address)](mailto:xuyx@lamda.nju.edu.cn), so that we can have more discussions before opening a draft PR on this feature ;-）

**Comment by xuyxu** [comment] 2021-04-29 08:17
Closed via #14.

**Closed by xuyxu** 2021-04-29 08:17 UTC
Labels: feature request
